inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-md
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - '\A\s*#'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
